[package]
name = "packet-redirect"
version = "0.1.0"
edition = "2021"

[dependencies]
# Errors
anyhow = "1.0.93"
# Async framework
tokio = { version = "1.37.0", features = ["full"] }
# Websockets 
tokio-tungstenite = "0.21.0"
futures = "0.3.30"           # for websocket.send()
